services:
  web:
    image: lobsterk/web-nginx-php
    container_name: new-web
    restart: always
    ports:
      - "8176:80"
    volumes:
      - ./www/:/var/www/www/  # Обратите внимание на изменение пути
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/php-fpm/php.ini:/etc/php/7.4/fpm/php.ini
      - ./.docker/php-fpm/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./www/:/var/www/www/

  redis:
    restart: unless-stopped
    image: redis:7.2.5-alpine
    command: --save "" --appendonly no

  mysql:
    image: 'mysql/mysql-server:8.0'
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'

volumes:
  mysql:
    driver: local