FROM reg.techhprof.ru/profitclicks/rtb-cabinet/php-fpm:8.3-prod as prod

RUN set -eux \
    && apk add --no-cache ffmpeg

COPY ./docker/install-scripts/protoc.sh /opt/install-scripts/
RUN chmod +x /opt/install-scripts/protoc.sh && /opt/install-scripts/protoc.sh

USER devilbox

WORKDIR /app

VOLUME /app/storage/app
VOLUME /app/storage/logs
VOLUME /app/vendor

ENV \
    COMPOSER_MEMORY_LIMIT="-1" \
    COMPOSER_ALLOW_SUPERUSER="1"
COPY --chown=devilbox:devilbox composer.json composer.lock artisan ./

RUN set -eux && composer -V && composer install \
    --no-dev \
    --no-interaction \
    --no-autoloader \
    --prefer-dist \
    --no-scripts \
    --no-plugins \
    --no-cache \
    --audit

COPY --chown=devilbox:devilbox bootstrap ./bootstrap/
COPY --chown=devilbox:devilbox public ./public/
COPY --chown=devilbox:devilbox storage ./storage/
COPY --chown=devilbox:devilbox config ./config/
COPY --chown=devilbox:devilbox lang ./lang/
COPY --chown=devilbox:devilbox database ./database/
COPY --chown=devilbox:devilbox routes ./routes/
COPY --chown=devilbox:devilbox resources ./resources/
COPY --chown=devilbox:devilbox proto ./proto/
COPY --chown=devilbox:devilbox app ./app/

RUN set -eux && composer install \
    --no-dev \
    --prefer-dist \
    --no-interaction \
    --optimize-autoloader \
    --classmap-authoritative \
    --apcu-autoloader \
    --audit

USER root

COPY docker/prod/supervisor.d/*.conf /etc/supervisor/conf.d/
COPY docker/prod/php.ini /etc/php-custom.d/user.ini
COPY docker/prod/php-fpm.conf /etc/php-fpm-custom.d/user.conf
COPY docker/prod/startup.sh /startup.1.d/laravel.sh
COPY --chmod=600 docker/prod/cron.d/* /etc/cron.d/

ARG DEBUG_ENTRYPOINT="2"
ENV DEBUG_ENTRYPOINT ${DEBUG_ENTRYPOINT}
ARG TIMEZONE="Europe/Moscow"
ENV TIMEZONE ${TIMEZONE}
ARG BUILD_DATE
ENV BUILD_DATE ${BUILD_DATE}
ARG BUILD_NUMBER
ENV BUILD_NUMBER ${BUILD_NUMBER}
ARG COMMIT_REF
ENV COMMIT_REF ${COMMIT_REF}

FROM reg.techhprof.ru/profitclicks/rtb-cabinet/php-fpm:8.3-work as work

RUN set -eux \
    && apk add --no-cache ffmpeg

COPY ./docker/install-scripts/protoc.sh /opt/install-scripts/
RUN chmod +x /opt/install-scripts/protoc.sh && /opt/install-scripts/protoc.sh

WORKDIR /app

COPY docker/work/supervisor.d/ /etc/supervisor/conf.d/
COPY docker/work/php.ini /etc/php-custom.d/user.ini
COPY docker/work/php-fpm.conf /etc/php-fpm-custom.d/user.conf
COPY docker/work/startup.sh /startup.1.d/laravel.sh
COPY --chmod=600 docker/work/cron.d/* /etc/cron.d/

RUN echo 'alias a="./artisan"' >> /home/${MY_USER}/.bashrc

ARG DEBUG_ENTRYPOINT="2"
ENV DEBUG_ENTRYPOINT ${DEBUG_ENTRYPOINT}
ARG TIMEZONE="Europe/Moscow"
ENV TIMEZONE ${TIMEZONE}
